// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wulnwjzcpuhmiliqdahb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bG53anpjcHVobWlsaXFkYWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MDY1MzQsImV4cCI6MjA3OTk4MjUzNH0.KwWwCSYhLoofaxrUHbTe-YINAqgfY6MM9XW54Tfhi6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});